menu:
  Home: /
  Archives: /archives
  About Us: /about_us
  Contact Us: /contact_us

excerpt_link: Read More
archive_yearly: false

widgets:
  - category
  - tag
  - tagcloud
  - recent_posts
  - blogroll

blogrolls:
  - Shinetech China: http://www.shinetechchina.com/
  - Shinetech China TianJin Dev Team: http://shinetechchina-tj.github.io

fancybox: true

duoshuo_shortname: 

google_analytics:
rss:
